services:
  mongodb:
    image: mongo:7.0
    container_name: social_network_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: social_network

volumes:
  mongodb_data: